package sternbach.software.geniandroidsdk.model

data class ProfileRequest(
    val fields: List<String>? = null,
    val ids: List<String>? = null,
    val only_ids: Boolean? = null
) {
    companion object {
        val ALL_FIELDS = listOf(
            "about_me",
            "baptism",
            "big_tree",
            "birth",
            "block_exists",
            "burial",
            "cause_of_death",
            "claimed",
            "created_at",
            "created_by",
            "creator",
            "curator",
            "current_residence",
            "death",
            "detail_strings",
            "display_name",
            "documents_updated_at",
            "email",
            "events",
            "first_name",
            "gender",
            "get_email",
            "guid",
            "id",
            "is_alive",
            "language",
            "last_name",
            "locked",
            "maiden_name",
            "managers",
            "master_profile",
            "merge_note",
            "merge_pending",
            "merged_into",
            "middle_name",
            "mugshot_urls",
            "name",
            "names",
            "nicknames",
            "occupation",
            "phone_numbers",
            "photos_updated_at",
            "premium_start_date",
            "profile_url",
            "public",
            "relationship",
            "requested_merges",
            "suffix",
            "unions",
            "updated_at",
            "url",
            "videos_updated_at",
        )
    }
}
